<?php

namespace Siesta\App\Command;

class MovieTransformer
{
    const SECTIONS_MAP = [
        "90-film_programme_sections" => "Noves Visions",
        "91-film_programme_sections" => "Sitges Documenta - Sessions especials",
        "93-film_programme_sections" => "Anima't - Fuera de Competición",
        "94-film_programme_sections" => "Oficial Fantàstic Competición - Cortos",
        "95-film_programme_sections" => "Sesiones Especiales",
        "96-film_programme_sections" => "Brigadoon ",
        "97-film_programme_sections" => "Oficial Fantàstic Competición",
        "98-film_programme_sections" => "Panorama Fantàstic",
        "99-film_programme_sections" => "Midnight X-Treme",
        "100-film_programme_sections" => "Anima’t",
        "102-film_programme_sections" => "Catalunya Imaginària",
        "103-film_programme_sections" => "Sitges Clàssics",
        "105-film_programme_sections" => "Sitges Clàssics - Focus Macros Ocultas",
        "106-film_programme_sections" => "Òrbita - Clausura",
        "107-film_programme_sections" => "Seven Chances",
        "108-film_programme_sections" => "Noves Visions - Petit Format",
        "110-film_programme_sections" => "Anima't - Cortos",
        "111-film_programme_sections" => "Oficial Fantàstic - Fuera De Competición",
        "112-film_programme_sections" => "Noves Visions - Sesión especial",
        "114-film_programme_sections" => "Clausura - Corto",
        "117-film_programme_sections" => "Inauguració",
        "118-film_programme_sections" => "Midnight X-Treme - Sesiones especiales",
        "120-film_programme_sections" => "Sitges Documenta",
        "123-film_programme_sections" => "Noves Visions - Clausura",
        "124-film_programme_sections" => "Òrbita",
        "125-film_programme_sections" => "Clausura",
        "126-film_programme_sections" => "Anima't - Inauguración",
        "129-film_programme_sections" => "Noves Visions - Inauguración",
        "618-film_programme_sections" => "Nueva autoría",
        "727-film_programme_sections" => "Anima't - Cortos",
        "728-film_programme_sections" => "Noves Visions",
        "729-film_programme_sections" => "Noves Visions - Inauguración",
        "732-film_programme_sections" => "Oficial Fantàstic Competición",
        "733-film_programme_sections" => "Noves Visions - Petit Format",
        "734-film_programme_sections" => "Sitges Clàssics",
        "739-film_programme_sections" => "Anima't - Sesión Especial",
        "741-film_programme_sections" => "Anima't",
        "742-film_programme_sections" => "Brigadoon",
        "744-film_programme_sections" => "Panorama",
        "746-film_programme_sections" => "Cloenda",
        "747-film_programme_sections" => "Oficial Fantàstic - Sesiones Especiales",
        "748-film_programme_sections" => "Oficial Fantàstic - Especial Medianoche",
        "750-film_programme_sections" => "Sesions Especiales - Cortos",
        "751-film_programme_sections" => "Sitges Documenta",
        "754-film_programme_sections" => "Òrbita",
        "755-film_programme_sections" => "Noves Visions - Clausura",
        "756-film_programme_sections" => "Nova Autoria - Sesiones Especiales",
        "758-film_programme_sections" => "Inauguración",
        "759-film_programme_sections" => "Catalunya Imaginària",
        "763-film_programme_sections" => "Seven Chances",
        "766-film_programme_sections" => "Sessió Sorpresa",
        "768-film_programme_sections" => "Oficial Fantàstic Competición - Cortos",
        "770-film_programme_sections" => "Serial Sitges",
        "772-film_programme_sections" => "Midnight X-Treme",
        "773-film_programme_sections" => "Noves Visions - Sesión Especial",
        "775-film_programme_sections" => "Panorama - Sesión Especial",
        "776-film_programme_sections" => "Sitges Clàssics - Ciudad Pánico",
        "777-film_programme_sections" => "Noves Visions - Petit Format - Sesión Especial",
        "778-film_programme_sections" => "Anima't - Sitges Clàssics",
        "779-film_programme_sections" => "Sitges Family - Kids",
        "780-film_programme_sections" => "Sitges Family - Teens",
        "835-film_programme_sections" => "Anima't",
        "837-film_programme_sections" => "Anima't - Curts",
        "839-film_programme_sections" => "Anima't - Sessió Especial",
        "841-film_programme_sections" => "Brigadoon",
        "842-film_programme_sections" => "Catalunya Imaginària",
        "843-film_programme_sections" => "Cloenda",
        "845-film_programme_sections" => "Inauguració",
        "848-film_programme_sections" => "Nova Autoria - Sessions Especials",
        "849-film_programme_sections" => "Noves Visions",
        "850-film_programme_sections" => "Noves Visions - Cloenda",
        "852-film_programme_sections" => "Noves Visions - Petit Format",
        "853-film_programme_sections" => "Noves Visions - Petit Format - Fora de Competició",
        "859-film_programme_sections" => "Oficial Fantàstic Competició",
        "860-film_programme_sections" => "Oficial Fantàstic Competició - Curts",
        "861-film_programme_sections" => "Sitges Collection",
        "862-film_programme_sections" => "Òrbita",
        "863-film_programme_sections" => "Òrbita - Cloenda",
        "865-film_programme_sections" => "Òrbita - Sessions Especials",
        "866-film_programme_sections" => "Panorama",
        "870-film_programme_sections" => "Retrospectiva",
        "871-film_programme_sections" => "Serial Sitges",
        "872-film_programme_sections" => "Sessió Escoles",
        "875-film_programme_sections" => "Sessions Especials",
        "876-film_programme_sections" => "Sessions Especials - Curts",
        "877-film_programme_sections" => "Seven Chances",
        "878-film_programme_sections" => "Sitges Clàssics",
        "881-film_programme_sections" => "Sitges Documenta",
        "884-film_programme_sections" => "Sitges Family - Kids",
        "885-film_programme_sections" => "Sitges Family - Teens",
        "886-film_programme_sections" => "Midnight X-Treme",
        "887-film_programme_sections" => "Sitges Family - Kids en Acció",
        "889-film_programme_sections" => "Sitges Collection - Sessió Especial",
    ];
    const LOCATIONS_MAP = [
        "359-location" => "Sala Tramuntana Meliá",
        "360-location" => "Biblioteca J. Roig i Raventós",
        "361-location" => "Sala Llevant",
        "362-location" => "Centre Cultural Miramar",
        "363-location" => "Jardí Meliá",
        "365-location" => "Hall Meliá",
        "366-location" => "Photocall Port",
        "367-location" => "Cinema Retiro",
        "368-location" => "Carpa Norai",
        "369-location" => "Xaloc 1",
        "370-location" => "Photocall Mirador",
        "372-location" => "Sala Girona Meliá",
        "373-location" => "Plaça de Catalunya (Sitges)",
        "374-location" => "Cinema Casino Prado",
        "375-location" => "Sala Garbí 1 Meliá",
        "376-location" => "Plataforma Online",
        "377-location" => "Fundació Ave Maria",
        "378-location" => "Platja de Sant Sebastià",
        "379-location" => "Set Fanlab",
        "380-location" => "Photocall Jardí Meliá",
        "381-location" => "Port d'Aiguadolç",
        "382-location" => "Exterior Hotel Meliá",
        "383-location" => "Mercat Vell",
        "385-location" => "ESCAC - Terrassa",
        "386-location" => "Sala Garbí 2 Meliá",
        "387-location" => "Palau Maricel",
        "388-location" => "Espai Jove",
        "389-location" => "Mercat Municipal",
        "390-location" => "Carpa Fnac",
        "391-location" => "Museu Maricel",
        "392-location" => "Sala Auditori Meliá",
        "393-location" => "Ermita de Sant Sebastià",
        "394-location" => "Hall Auditori Meliá",
        "395-location" => "Jardí Prado",
        "947-location" => "En línia",
        "6333-location" => "Cinema Escorxador",
        "6334-location" => "Exterior Miramar",
    ];

    public function fromCategoryDataToCategory(string $sectionData): string
    {
        return array_key_exists($sectionData, self::SECTIONS_MAP)
            ? self::SECTIONS_MAP[$sectionData]
            : '';
    }

    public function fromDataLocationToLocation(string $location)
    {
        return array_key_exists($location, self::LOCATIONS_MAP)
            ? self::LOCATIONS_MAP[$location]
            : 'idk';
    }

}