version: "3.8"

services:
    php:
        build: .
        ports:
            -   "8080:80"
        volumes:
            - .:/var/www/html

 
    db:
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: siesta
            MYSQL_USER: siesta
            MYSQL_PASSWORD: siesta
        ports:
            - "33060:3306"
        volumes:
          - ./docker/db/data:/var/lib/mysql:rw
