## Get movie
GET http://localhost:8080/movie/1
Accept: application/json

### get movie with header
GET http://localhost:8080/movie/4226
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

### get all movies
GET http://localhost:8080/film-festival/7/movies
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

### Get votes for movie
GET http://localhost:8080/movie/4226/votes
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

###
POST http://localhost:8080/movie/3722/vote
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

[{"user_id":"1","score":"-1","user_name":"Sandra"},{"user_id":"11","score":"0","user_name":"Unai"},{"user_id":"21","score":"1","user_name":"Dave"},{"user_id":"31","score":"2","user_name":"Putojebi"},{"user_id":"41","score":"-1","user_name":"Leticia"}]
<> 2024-08-25T100955.201.json

### Login

POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "davekrelak@hotmail.com",
  "password" : "123456"
}

### LOGIN PRO

POST https://darkslateblue-walrus-393957.hostingersite.com/login
Content-Type: application/json

{
  "email": "davekrelak@hotmail.com",
  "password" : "123456"
}


### OPTIONS PRO

OPTIONS https://darkslateblue-walrus-393957.hostingersite.com/login


### Last movie voted
GET http://localhost:8080/film-festival/99/next
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

### Users from group
GET http://localhost:8080/group/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4
### Chat with the agent
POST http://localhost:8080/agent/chat
Content-Type: application/json
Accept: text/event-stream
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

{
  "conversation_id": "3f6c1a2b9d4e4f0a8b7c6d5e4f3a2b1c",
  "message": "¿Qué me recomiendas ver este año?",
  "context": {
    "movie_title": "Titane",
    "movie_year": 2021
  }
}

### Chat with the agent - empty message, answers 400 instead of opening the stream
POST http://localhost:8080/agent/chat
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

{
  "message": ""
}

### Clear a wrong trailer of a movie
PATCH http://localhost:8080/movie/1/media
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

{
  "trailer": null
}

### Replace the poster of a movie, the trailer stays as it is
PATCH http://localhost:8080/movie/1/media
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

{
  "poster": "https://image.tmdb.org/t/p/w500/right-poster.jpg"
}

### Name a movie the way the group calls it
PATCH http://localhost:8080/movie/1/alias
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

{
  "alias": "La de los pingüinos"
}

### Clear the alias of a movie, it goes back to being known by its title
PATCH http://localhost:8080/movie/1/alias
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjEiLCJ1c2VyX25hbWUiOiJEYXZlIiwiZ3JvdXBfaWQiOiIxIiwiZ3JvdXBfbmFtZSI6IlRvbCBHcml0byJ9.Q2RMEFhaqAsSHjJhrcbc22eBSOGbms7D_V-LK34AvZ4

{
  "alias": null
}
