get-movie:
    path: /movie/{id}
    controller: Siesta\App\Action\Movie\GetMovieByIdAction
    methods: GET

update-movie-media:
    path: /movie/{movieId}/media
    controller: Siesta\App\Action\Movie\UpdateMovieMediaAction
    methods: PATCH

get-votes-for-movie:
    path: /movie/{movieId}/votes
    controller: Siesta\App\Action\Vote\GetVotesForMovieAction
    methods: GET
vote-for-movie:
    path: /movie/{movieId}/vote
    controller: Siesta\App\Action\Vote\VoteForMovieAction
    methods: POST

rate-movie:
    path: /movie/{movieId}/rating
    controller: Siesta\App\Action\Rating\RateMovieAction
    methods: POST

movie-ratings-of-film-festival:
    path: /film-festival/{filmFestivalId}/ratings
    controller: Siesta\App\Action\Rating\GetMovieRatingsAction
    methods: GET

agent-chat:
    path: /agent/chat
    controller: Siesta\App\Action\Agent\ChatWithAgentAction
    methods: POST

get-film-festivals:
    path: /film-festival
    controller: Siesta\App\Action\FilmFestival\GetAllFilmFestivalsAction
    methods: GET

last-movie-voted-for-user:
    path: /film-festival/{filmFestivalId}/next
    controller: Siesta\App\Action\Vote\GetNextMovieToVoteAction
    methods: GET

pending-votes-count-for-user:
    path: /film-festival/{filmFestivalId}/pending-votes
    controller: Siesta\App\Action\Vote\GetPendingVotesCountAction
    methods: GET

all-movies-of-film-festival:
    path: /film-festival/{filmFestivalId}/movies
    controller: Siesta\App\Action\Movie\GetAllMoviesAction
    methods: GET

login-user:
    path: /login
    controller: Siesta\App\Action\User\LoginUserAction
    methods: POST

users-from-group:
    path: /group/{groupId}
    controller: Siesta\App\Action\User\UserListFromGroupAction
    methods: GET