get-movie:
    path: /movie/{id}
    controller: Siesta\App\Action\Movie\GetMovieByIdAction
    methods: GET

get-votes-for-movie:
    path: /movie/{movieId}/votes
    controller: Siesta\App\Action\Vote\GetVotesForMovieAction
    methods: GET
vote-for-movie:
    path: /movie/{movieId}/vote
    controller: Siesta\App\Action\Vote\VoteForMovieAction
    methods: POST

last-movie-voted-for-user:
    path: /film-festival/{filmFestivalId}/last-voted
    controller: Siesta\App\Action\Vote\GetLastMovieVotedAction
    methods: GET

login-user:
    path: /login
    controller: Siesta\App\Action\User\LoginUserAction
    methods: POST